# permissions for end users to view egressprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: egressprofile-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: egress-guardian-operator
    app.kubernetes.io/part-of: egress-guardian-operator
    app.kubernetes.io/managed-by: kustomize
  name: egressprofile-viewer-role
rules:
- apiGroups:
  - egress.platform.io
  resources:
  - egressprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - egress.platform.io
  resources:
  - egressprofiles/status
  verbs:
  - get
